apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - secret.sops.yaml
  - service-headless.yaml
  - service.yaml
  - statefulset.yaml
commonLabels:
  app.kubernetes.io/name: mongodb
